version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist s3://travelgenius-ui --delete

cache:
  paths:
    - node_modules/**/*
